### ISSUE TITLE
Undefined variable in output text

### ISSUE THREAD

**Issue by kethinov** [rooseveltframework/mkroosevelt#160]
`npx mkroosevelt`

This text renders: `Change to your app directory:  cd undefined`

Could be an issue with the [generator](https://github.com/rooseveltframework/generator-roosevelt) itself.

**Comment by Arindam200** [comment]
Can I contribute to this?

**Comment by kethinov** [comment]
Go for it!

**Comment by kethinov** [comment]
This was fixed in 0.21.7
